// AUTO-GENERATED by scripts/build-merger-annotations.mjs
// Do not edit by hand. Re-run script after pingshui.json changes.
//
// Source: src/data/pingshui.json + opencc-js (cn/tw mode).
// Filter: simp→multi-trad where trads have classically-distinct
// 平水韻 rhyme placements (丰/豐 pattern). See #7 ticket / Part 1
// design for the precision-tuned filter pipeline.

export interface MergerForm {
  trad: string;
  /** sorted unique 平水韻 rhyme labels this trad appears in */
  rhymes: string[];
  /** sorted unique tone categories (平 / 入 / 仄) */
  tones: ReadonlyArray<'平' | '仄' | '入'>;
  /** Optional gloss; empty in this generation. Future ticket may auto-pop from MOE. */
  meaning?: string;
  /** True if this trad is what `opencc t2s(simp)` returns (the analyzer's current default). */
  isOpenccDefault: boolean;
}

export interface MergerAnnotation {
  /** the merged simp form (also the Record key) */
  simp: string;
  /** 2+ trad forms with their classical placements; sorted by codepoint */
  forms: MergerForm[];
  /** what `opencc t2s(simp)` returns; duplicates one form's `trad` for fast lookup */
  openccDefault: string;
  /** Optional human-curated note; empty in this generation. Render only when populated. */
  pedagogicalNote?: string;
}

/** Map of simp char → annotation. O(1) lookup. */
export const MERGER_ANNOTATIONS: Record<string, MergerAnnotation> = {
  '㐹': {
    simp: '㐹',
    openccDefault: '㑶',
    forms: [
      { trad: '㐹', rhymes: ['五物'], tones: ['入'], isOpenccDefault: false },
      { trad: '㑶', rhymes: ['四寘'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '䇲': {
    simp: '䇲',
    openccDefault: '筴',
    forms: [
      { trad: '䇲', rhymes: ['十一陌'], tones: ['入'], isOpenccDefault: false },
      { trad: '筴', rhymes: ['十一陌', '十七洽', '十六葉'], tones: ['入'], isOpenccDefault: true },
    ],
  },
  '丰': {
    simp: '丰',
    openccDefault: '豐',
    forms: [
      { trad: '丰', rhymes: ['二冬'], tones: ['平'], isOpenccDefault: false },
      { trad: '豐', rhymes: ['一東'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '么': {
    simp: '么',
    openccDefault: '麼',
    forms: [
      { trad: '么', rhymes: ['二蕭'], tones: ['平'], isOpenccDefault: false },
      { trad: '麼', rhymes: ['二十哿', '五歌'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '麽', rhymes: ['二十哿', '五歌'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '伙': {
    simp: '伙',
    openccDefault: '夥',
    forms: [
      { trad: '伙', rhymes: ['二十哿'], tones: ['仄'], isOpenccDefault: false },
      { trad: '夥', rhymes: ['九蟹', '二十哿'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '伣': {
    simp: '伣',
    openccDefault: '俔',
    forms: [
      { trad: '伣', rhymes: ['九屑', '十七霰'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '俔', rhymes: ['十七霰'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '侥': {
    simp: '侥',
    openccDefault: '僥',
    forms: [
      { trad: '侥', rhymes: ['二蕭', '十七筱'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '僥', rhymes: ['二蕭'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '冲': {
    simp: '冲',
    openccDefault: '衝',
    forms: [
      { trad: '冲', rhymes: ['一東'], tones: ['平'], isOpenccDefault: false },
      { trad: '沖', rhymes: ['一東'], tones: ['平'], isOpenccDefault: false },
      { trad: '衝', rhymes: ['二冬'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '凌': {
    simp: '凌',
    openccDefault: '凌',
    forms: [
      { trad: '凌', rhymes: ['二十五徑', '十蒸'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '淩', rhymes: ['十蒸'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '几': {
    simp: '几',
    openccDefault: '幾',
    forms: [
      { trad: '几', rhymes: ['五尾', '五微', '四寘', '四紙'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '幾', rhymes: ['五尾', '五微', '四寘'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '凭': {
    simp: '凭',
    openccDefault: '憑',
    forms: [
      { trad: '凭', rhymes: ['二十五徑', '十蒸'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '憑', rhymes: ['十蒸'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '出': {
    simp: '出',
    openccDefault: '出',
    forms: [
      { trad: '出', rhymes: ['四寘', '四質'], tones: ['入', '仄'], isOpenccDefault: true },
      { trad: '齣', rhymes: ['四質'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '别': {
    simp: '别',
    openccDefault: '別',
    forms: [
      { trad: '別', rhymes: ['九屑'], tones: ['入'], isOpenccDefault: true },
      { trad: '别', rhymes: ['九屑'], tones: ['入'], isOpenccDefault: false },
      { trad: '彆', rhymes: ['九屑', '八霽'], tones: ['入', '仄'], isOpenccDefault: false },
    ],
  },
  '卷': {
    simp: '卷',
    openccDefault: '卷',
    forms: [
      { trad: '卷', rhymes: ['一先', '十七霰', '十六銑'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '捲', rhymes: ['一先', '十六銑'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '厂': {
    simp: '厂',
    openccDefault: '廠',
    forms: [
      { trad: '厂', rhymes: ['十五翰', '十四旱'], tones: ['仄'], isOpenccDefault: false },
      { trad: '廠', rhymes: ['二十二養'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '参': {
    simp: '参',
    openccDefault: '參',
    forms: [
      { trad: '参', rhymes: ['二十七感', '二十八勘', '十三覃', '十二侵'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '參', rhymes: ['二十七感', '二十八勘', '十三覃', '十二侵'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '蔘', rhymes: ['十二侵'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '叠': {
    simp: '叠',
    openccDefault: '疊',
    forms: [
      { trad: '叠', rhymes: ['九屑'], tones: ['入'], isOpenccDefault: false },
      { trad: '疊', rhymes: ['十六葉'], tones: ['入'], isOpenccDefault: true },
    ],
  },
  '台': {
    simp: '台',
    openccDefault: '臺',
    forms: [
      { trad: '台', rhymes: ['十灰', '四支'], tones: ['平'], isOpenccDefault: false },
      { trad: '檯', rhymes: ['十灰'], tones: ['平'], isOpenccDefault: false },
      { trad: '臺', rhymes: ['十灰'], tones: ['平'], isOpenccDefault: true },
      { trad: '颱', rhymes: ['十灰'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '同': {
    simp: '同',
    openccDefault: '同',
    forms: [
      { trad: '同', rhymes: ['一東'], tones: ['平'], isOpenccDefault: true },
      { trad: '衕', rhymes: ['一東', '一送'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '听': {
    simp: '听',
    openccDefault: '聽',
    forms: [
      { trad: '听', rhymes: ['九青', '十二吻'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '聽', rhymes: ['九青'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '咽': {
    simp: '咽',
    openccDefault: '咽',
    forms: [
      { trad: '咽', rhymes: ['一先', '九屑', '十七霰'], tones: ['平', '入', '仄'], isOpenccDefault: true },
      { trad: '嚥', rhymes: ['十七霰'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '哄': {
    simp: '哄',
    openccDefault: '哄',
    forms: [
      { trad: '哄', rhymes: ['一東', '一送'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '鬨', rhymes: ['一送', '三絳'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '唝': {
    simp: '唝',
    openccDefault: '嗊',
    forms: [
      { trad: '唝', rhymes: ['一董'], tones: ['仄'], isOpenccDefault: false },
      { trad: '嗊', rhymes: ['一董', '一送'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '啮': {
    simp: '啮',
    openccDefault: '齧',
    forms: [
      { trad: '啮', rhymes: ['十八巧'], tones: ['仄'], isOpenccDefault: false },
      { trad: '嚙', rhymes: ['九屑', '十八巧'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '齧', rhymes: ['九屑'], tones: ['入'], isOpenccDefault: true },
    ],
  },
  '坛': {
    simp: '坛',
    openccDefault: '壇',
    forms: [
      { trad: '坛', rhymes: ['十四寒'], tones: ['平'], isOpenccDefault: false },
      { trad: '壇', rhymes: ['十四寒'], tones: ['平'], isOpenccDefault: true },
      { trad: '壜', rhymes: ['十三覃'], tones: ['平'], isOpenccDefault: false },
      { trad: '罈', rhymes: ['十三覃'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '奸': {
    simp: '奸',
    openccDefault: '奸',
    forms: [
      { trad: '奸', rhymes: ['十五刪', '十四寒'], tones: ['平'], isOpenccDefault: true },
      { trad: '姦', rhymes: ['十五刪'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '姹': {
    simp: '姹',
    openccDefault: '奼',
    forms: [
      { trad: '奼', rhymes: ['七遇', '二十一馬', '二十二禡'], tones: ['仄'], isOpenccDefault: true },
      { trad: '姹', rhymes: ['七遇', '二十二禡'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '宁': {
    simp: '宁',
    openccDefault: '寧',
    forms: [
      { trad: '宁', rhymes: ['九青', '六語'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '寧', rhymes: ['九青'], tones: ['平'], isOpenccDefault: true },
      { trad: '甯', rhymes: ['九青'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '家': {
    simp: '家',
    openccDefault: '家',
    forms: [
      { trad: '傢', rhymes: ['二十二養'], tones: ['仄'], isOpenccDefault: false },
      { trad: '家', rhymes: ['六麻'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '干': {
    simp: '干',
    openccDefault: '幹',
    forms: [
      { trad: '乾', rhymes: ['一先', '十四寒'], tones: ['平'], isOpenccDefault: false },
      { trad: '干', rhymes: ['十五翰', '十四寒'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '幹', rhymes: ['十五翰'], tones: ['仄'], isOpenccDefault: true },
      { trad: '榦', rhymes: ['十五翰'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '广': {
    simp: '广',
    openccDefault: '廣',
    forms: [
      { trad: '广', rhymes: ['二十八琰'], tones: ['仄'], isOpenccDefault: false },
      { trad: '廣', rhymes: ['二十二養'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '弥': {
    simp: '弥',
    openccDefault: '彌',
    forms: [
      { trad: '弥', rhymes: ['四支', '四紙'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '彌', rhymes: ['四支', '四紙'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '瀰', rhymes: ['八薺', '四支', '四紙'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '征': {
    simp: '征',
    openccDefault: '徵',
    forms: [
      { trad: '征', rhymes: ['八庚'], tones: ['平'], isOpenccDefault: false },
      { trad: '徵', rhymes: ['十蒸', '四紙'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '御': {
    simp: '御',
    openccDefault: '御',
    forms: [
      { trad: '御', rhymes: ['六御'], tones: ['仄'], isOpenccDefault: true },
      { trad: '禦', rhymes: ['六語'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '折': {
    simp: '折',
    openccDefault: '折',
    forms: [
      { trad: '折', rhymes: ['九屑', '八齊'], tones: ['平', '入'], isOpenccDefault: true },
      { trad: '摺', rhymes: ['十六葉'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '据': {
    simp: '据',
    openccDefault: '據',
    forms: [
      { trad: '据', rhymes: ['六御', '六魚'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '據', rhymes: ['六御'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '揾': {
    simp: '揾',
    openccDefault: '搵',
    forms: [
      { trad: '揾', rhymes: ['十二吻', '十四願'], tones: ['仄'], isOpenccDefault: false },
      { trad: '搵', rhymes: ['六月', '十二吻', '十二文', '十四願'], tones: ['平', '入', '仄'], isOpenccDefault: true },
    ],
  },
  '旗': {
    simp: '旗',
    openccDefault: '旗',
    forms: [
      { trad: '旂', rhymes: ['五微'], tones: ['平'], isOpenccDefault: false },
      { trad: '旗', rhymes: ['四支'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '暗': {
    simp: '暗',
    openccDefault: '暗',
    forms: [
      { trad: '暗', rhymes: ['二十八勘', '十七霰'], tones: ['仄'], isOpenccDefault: true },
      { trad: '闇', rhymes: ['二十七感', '二十九豏', '二十八勘', '二十六寢', '十三覃', '十二侵'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '曲': {
    simp: '曲',
    openccDefault: '曲',
    forms: [
      { trad: '曲', rhymes: ['二沃'], tones: ['入'], isOpenccDefault: true },
      { trad: '麯', rhymes: ['一屋'], tones: ['入'], isOpenccDefault: false },
      { trad: '麴', rhymes: ['一屋'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '术': {
    simp: '术',
    openccDefault: '術',
    forms: [
      { trad: '朮', rhymes: ['四質'], tones: ['入'], isOpenccDefault: false },
      { trad: '术', rhymes: ['四寘', '四質'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '術', rhymes: ['四寘', '四質'], tones: ['入', '仄'], isOpenccDefault: true },
    ],
  },
  '机': {
    simp: '机',
    openccDefault: '機',
    forms: [
      { trad: '机', rhymes: ['五微', '四紙'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '機', rhymes: ['五微'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '核': {
    simp: '核',
    openccDefault: '核',
    forms: [
      { trad: '核', rhymes: ['六月', '十一陌'], tones: ['入'], isOpenccDefault: true },
      { trad: '覈', rhymes: ['九屑', '十一陌'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '梿': {
    simp: '梿',
    openccDefault: '槤',
    forms: [
      { trad: '梿', rhymes: ['一先'], tones: ['平'], isOpenccDefault: false },
      { trad: '槤', rhymes: ['一先', '十六銑'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '汇': {
    simp: '汇',
    openccDefault: '匯',
    forms: [
      { trad: '匯', rhymes: ['十賄'], tones: ['仄'], isOpenccDefault: true },
      { trad: '彙', rhymes: ['五未'], tones: ['仄'], isOpenccDefault: false },
      { trad: '汇', rhymes: ['十賄'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '沾': {
    simp: '沾',
    openccDefault: '沾',
    forms: [
      { trad: '沾', rhymes: ['二十九艷', '十四鹽'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '霑', rhymes: ['十四鹽'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '泛': {
    simp: '泛',
    openccDefault: '泛',
    forms: [
      { trad: '汎', rhymes: ['一東', '三十陷'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '泛', rhymes: ['三十陷'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '涂': {
    simp: '涂',
    openccDefault: '塗',
    forms: [
      { trad: '塗', rhymes: ['七虞', '六麻'], tones: ['平'], isOpenccDefault: true },
      { trad: '涂', rhymes: ['七虞', '六魚', '六麻'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '溇': {
    simp: '溇',
    openccDefault: '漊',
    forms: [
      { trad: '溇', rhymes: ['七虞', '二十五有'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '漊', rhymes: ['七虞', '二十五有', '十一尤'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '牦': {
    simp: '牦',
    openccDefault: '犛',
    forms: [
      { trad: '氂', rhymes: ['四支', '四豪'], tones: ['平'], isOpenccDefault: false },
      { trad: '牦', rhymes: ['四豪'], tones: ['平'], isOpenccDefault: false },
      { trad: '犛', rhymes: ['三肴', '四支'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '璇': {
    simp: '璇',
    openccDefault: '璇',
    forms: [
      { trad: '璇', rhymes: ['一先'], tones: ['平'], isOpenccDefault: true },
      { trad: '璿', rhymes: ['一先', '八霽'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '着': {
    simp: '着',
    openccDefault: '著',
    forms: [
      { trad: '着', rhymes: ['十藥'], tones: ['入'], isOpenccDefault: false },
      { trad: '著', rhymes: ['六御', '六語', '十藥'], tones: ['入', '仄'], isOpenccDefault: true },
    ],
  },
  '睾': {
    simp: '睾',
    openccDefault: '睪',
    forms: [
      { trad: '睪', rhymes: ['十一陌'], tones: ['入'], isOpenccDefault: true },
      { trad: '睾', rhymes: ['十一陌', '四豪'], tones: ['平', '入'], isOpenccDefault: false },
    ],
  },
  '硙': {
    simp: '硙',
    openccDefault: '磑',
    forms: [
      { trad: '硙', rhymes: ['十一隊'], tones: ['仄'], isOpenccDefault: false },
      { trad: '磑', rhymes: ['十一隊', '十灰'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '硷': {
    simp: '硷',
    openccDefault: '礆',
    forms: [
      { trad: '硷', rhymes: ['二十九艷', '二十九豏', '十四鹽'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '礆', rhymes: ['二十八琰'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '种': {
    simp: '种',
    openccDefault: '種',
    forms: [
      { trad: '种', rhymes: ['一東', '二宋', '二腫'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '種', rhymes: ['二宋', '二腫'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '箓': {
    simp: '箓',
    openccDefault: '籙',
    forms: [
      { trad: '箓', rhymes: ['七遇', '二沃'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '籙', rhymes: ['二沃'], tones: ['入'], isOpenccDefault: true },
    ],
  },
  '缊': {
    simp: '缊',
    openccDefault: '縕',
    forms: [
      { trad: '緼', rhymes: ['十三元', '十二吻', '十二文'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '縕', rhymes: ['十三元', '十三問', '十二吻', '十二文'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '缊', rhymes: ['十三元', '十二吻', '十二文'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '翙': {
    simp: '翙',
    openccDefault: '翽',
    forms: [
      { trad: '翙', rhymes: ['九泰', '五物'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '翽', rhymes: ['九泰'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '肮': {
    simp: '肮',
    openccDefault: '骯',
    forms: [
      { trad: '肮', rhymes: ['七陽', '二十二養'], tones: ['平', '仄'], isOpenccDefault: false },
      { trad: '骯', rhymes: ['二十二養'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '脏': {
    simp: '脏',
    openccDefault: '髒',
    forms: [
      { trad: '臟', rhymes: ['二十二養'], tones: ['仄'], isOpenccDefault: false },
      { trad: '髒', rhymes: ['二十三漾', '二十二養'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '舍': {
    simp: '舍',
    openccDefault: '舍',
    forms: [
      { trad: '捨', rhymes: ['二十一馬'], tones: ['仄'], isOpenccDefault: false },
      { trad: '舍', rhymes: ['二十一馬', '二十二禡'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '苹': {
    simp: '苹',
    openccDefault: '蘋',
    forms: [
      { trad: '苹', rhymes: ['八庚'], tones: ['平'], isOpenccDefault: false },
      { trad: '蘋', rhymes: ['十一真'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '获': {
    simp: '获',
    openccDefault: '獲',
    forms: [
      { trad: '獲', rhymes: ['十一陌', '十藥'], tones: ['入'], isOpenccDefault: true },
      { trad: '穫', rhymes: ['七遇', '十一陌', '十藥'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '获', rhymes: ['十一陌', '十藥'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '蔂': {
    simp: '蔂',
    openccDefault: '虆',
    forms: [
      { trad: '蔂', rhymes: ['四支'], tones: ['平'], isOpenccDefault: false },
      { trad: '虆', rhymes: ['五歌', '四支', '四紙'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '虮': {
    simp: '虮',
    openccDefault: '蟣',
    forms: [
      { trad: '虮', rhymes: ['四支'], tones: ['平'], isOpenccDefault: false },
      { trad: '蟣', rhymes: ['五尾', '五微', '四支'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '蝎': {
    simp: '蝎',
    openccDefault: '蠍',
    forms: [
      { trad: '蝎', rhymes: ['七曷'], tones: ['入'], isOpenccDefault: false },
      { trad: '蠍', rhymes: ['六月'], tones: ['入'], isOpenccDefault: true },
    ],
  },
  '蟏': {
    simp: '蟏',
    openccDefault: '蠨',
    forms: [
      { trad: '蟏', rhymes: ['二蕭'], tones: ['平'], isOpenccDefault: false },
      { trad: '蠨', rhymes: ['一屋', '二蕭'], tones: ['平', '入'], isOpenccDefault: true },
    ],
  },
  '袅': {
    simp: '袅',
    openccDefault: '嫋',
    forms: [
      { trad: '嫋', rhymes: ['十七筱', '十藥'], tones: ['入', '仄'], isOpenccDefault: true },
      { trad: '袅', rhymes: ['十七筱'], tones: ['仄'], isOpenccDefault: false },
      { trad: '裊', rhymes: ['十七筱'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '訚': {
    simp: '訚',
    openccDefault: '誾',
    forms: [
      { trad: '訚', rhymes: ['十一真'], tones: ['平'], isOpenccDefault: false },
      { trad: '誾', rhymes: ['十一真', '十二文'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '证': {
    simp: '证',
    openccDefault: '證',
    forms: [
      { trad: '証', rhymes: ['二十四敬'], tones: ['仄'], isOpenccDefault: false },
      { trad: '證', rhymes: ['二十五徑', '二十四敬'], tones: ['仄'], isOpenccDefault: true },
      { trad: '证', rhymes: ['二十五徑', '二十四敬'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '说': {
    simp: '说',
    openccDefault: '說',
    forms: [
      { trad: '說', rhymes: ['八霽'], tones: ['仄'], isOpenccDefault: true },
      { trad: '説', rhymes: ['九屑', '八霽'], tones: ['入', '仄'], isOpenccDefault: false },
      { trad: '说', rhymes: ['八霽'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '轪': {
    simp: '轪',
    openccDefault: '軑',
    forms: [
      { trad: '軑', rhymes: ['九泰', '八霽'], tones: ['仄'], isOpenccDefault: true },
      { trad: '轪', rhymes: ['八霽', '十二錫'], tones: ['入', '仄'], isOpenccDefault: false },
    ],
  },
  '采': {
    simp: '采',
    openccDefault: '採',
    forms: [
      { trad: '埰', rhymes: ['十一隊', '十賄'], tones: ['仄'], isOpenccDefault: false },
      { trad: '寀', rhymes: ['十賄'], tones: ['仄'], isOpenccDefault: false },
      { trad: '采', rhymes: ['十一隊', '十賄'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '里': {
    simp: '里',
    openccDefault: '裡',
    forms: [
      { trad: '裏', rhymes: ['四寘', '四紙'], tones: ['仄'], isOpenccDefault: false },
      { trad: '裡', rhymes: ['四寘', '四紙'], tones: ['仄'], isOpenccDefault: true },
      { trad: '里', rhymes: ['四紙'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '钎': {
    simp: '钎',
    openccDefault: '釺',
    forms: [
      { trad: '釺', rhymes: ['十五翰', '十四寒'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '钎', rhymes: ['十五翰'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '铻': {
    simp: '铻',
    openccDefault: '鋙',
    forms: [
      { trad: '鋙', rhymes: ['六語', '六魚'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '铻', rhymes: ['六魚'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '锤': {
    simp: '锤',
    openccDefault: '錘',
    forms: [
      { trad: '錘', rhymes: ['四寘', '四支'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '鎚', rhymes: ['十灰', '四支'], tones: ['平'], isOpenccDefault: false },
      { trad: '锤', rhymes: ['四寘', '四支'], tones: ['平', '仄'], isOpenccDefault: false },
    ],
  },
  '镢': {
    simp: '镢',
    openccDefault: '钁',
    forms: [
      { trad: '鐝', rhymes: ['六月'], tones: ['入'], isOpenccDefault: false },
      { trad: '钁', rhymes: ['十藥'], tones: ['入'], isOpenccDefault: true },
      { trad: '镢', rhymes: ['六月'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '闲': {
    simp: '闲',
    openccDefault: '閒',
    forms: [
      { trad: '閑', rhymes: ['十五刪'], tones: ['平'], isOpenccDefault: false },
      { trad: '閒', rhymes: ['十五刪', '十六諫'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '闲', rhymes: ['十五刪'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '陕': {
    simp: '陕',
    openccDefault: '陝',
    forms: [
      { trad: '陕', rhymes: ['十七洽'], tones: ['入'], isOpenccDefault: false },
      { trad: '陝', rhymes: ['二十八琰'], tones: ['仄'], isOpenccDefault: true },
    ],
  },
  '霉': {
    simp: '霉',
    openccDefault: '黴',
    forms: [
      { trad: '霉', rhymes: ['十灰'], tones: ['平'], isOpenccDefault: false },
      { trad: '黴', rhymes: ['四支'], tones: ['平'], isOpenccDefault: true },
    ],
  },
  '鞲': {
    simp: '鞲',
    openccDefault: '韝',
    forms: [
      { trad: '鞲', rhymes: ['十一尤'], tones: ['平'], isOpenccDefault: false },
      { trad: '韝', rhymes: ['二十六宥', '十一尤'], tones: ['平', '仄'], isOpenccDefault: true },
    ],
  },
  '颎': {
    simp: '颎',
    openccDefault: '熲',
    forms: [
      { trad: '熲', rhymes: ['九青', '二十四迥'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '颎', rhymes: ['二十四迥'], tones: ['仄'], isOpenccDefault: false },
    ],
  },
  '饥': {
    simp: '饥',
    openccDefault: '飢',
    forms: [
      { trad: '飢', rhymes: ['四支'], tones: ['平'], isOpenccDefault: true },
      { trad: '饑', rhymes: ['五微'], tones: ['平'], isOpenccDefault: false },
      { trad: '饥', rhymes: ['五微'], tones: ['平'], isOpenccDefault: false },
    ],
  },
  '骕': {
    simp: '骕',
    openccDefault: '驌',
    forms: [
      { trad: '驌', rhymes: ['一屋'], tones: ['入'], isOpenccDefault: true },
      { trad: '骕', rhymes: ['一屋', '三覺'], tones: ['入'], isOpenccDefault: false },
    ],
  },
  '鳀': {
    simp: '鳀',
    openccDefault: '鯷',
    forms: [
      { trad: '鯷', rhymes: ['八霽', '八齊'], tones: ['平', '仄'], isOpenccDefault: true },
      { trad: '鳀', rhymes: ['八霽', '六月'], tones: ['入', '仄'], isOpenccDefault: false },
    ],
  },
  '鹔': {
    simp: '鹔',
    openccDefault: '鷫',
    forms: [
      { trad: '鷫', rhymes: ['一屋'], tones: ['入'], isOpenccDefault: true },
      { trad: '鹔', rhymes: ['一屋', '七遇'], tones: ['入', '仄'], isOpenccDefault: false },
    ],
  },
  '龁': {
    simp: '龁',
    openccDefault: '齕',
    forms: [
      { trad: '齕', rhymes: ['九屑', '六月'], tones: ['入'], isOpenccDefault: true },
      { trad: '龁', rhymes: ['六月'], tones: ['入'], isOpenccDefault: false },
    ],
  },
};

/**
 * Auto-generated default note when curated `pedagogicalNote` is empty.
 * Format: "[simp] 在平水韻中可指 [trad1] ([rhyme1]) 或 [trad2] ([rhyme2]) ..."
 *
 * Not auto-rendered in EditModal/RhymeCharCard banners — call sites that
 * want a fallback note when `pedagogicalNote` is empty can use this.
 */
export function defaultNote(annotation: MergerAnnotation): string {
  const parts = annotation.forms.map((f) => `${f.trad} (${f.rhymes.join(' / ')})`);
  return `${annotation.simp} 在平水韻中可指 ${parts.join(' 或 ')}`;
}
